BEGIN;

CREATE TABLE IF NOT EXISTS recommendations (
  id VARCHAR(255) PRIMARY KEY,
  book_id VARCHAR(255) NOT NULL,
  user_id VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE
);

COMMIT;