BEGIN;

CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(100) PRIMARY KEY NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

COMMIT;